[project]
name = "projectmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beeai-framework>=0.1.16",
    "mcp[cli]>=1.6.0",
    "pandas>=2.2.3",
]
